### ISSUE TITLE
WLCS testing tracking issue

### ISSUE THREAD

**Issue by vberger** [Smithay/smithay#639]
List of the WLCS tests, and the associated CI run that takes care of them:

- Core Tests (`core`):
  - [x] FrameSubmission.
  - [x] SelfTest.
- Output Tests (`output`):
  - [x] XdgOutputV1Test.
- Pointer Input tests (`pointer-input`):
  - [x] PointerCrossingSurfaceCorner/SurfacePointerMotionTest.
  - [x] PointerCrossingSurfaceEdge/SurfacePointerMotionTest.

Currently untested:
- [ ] BadBufferTest.
- [ ] SecondBadBufferTest.
- [ ] PointerConstraints.
- [ ] CopyCutPaste.
- [ ] GtkPrimarySelection.
- [ ] ClientSurfaceEventsTest.
- [ ] WlOutputTest.
- [ ] PrimarySelection.
- [ ] RelativePointer.
- [ ] XdgSurfaceV6Test.
- [ ] XdgToplevelV6Test.
- [ ] XdgToplevelV6ConfigurationTest.
- [ ] XdgSurfaceStableTest.
- [ ] XdgToplevelStableTest.
- [ ] XdgToplevelStableConfigurationTest.
- [ ] XdgPopupTest.
- [ ] LayerSurfaceTest.
- [ ] ForeignToplevelManagerTest.
- [ ] ForeignToplevelHandleTest.
- [ ] TextInputV3WithInputMethodV2Test.
- [ ] AllSurfaceTypes/TouchTest.
- [ ] MultiRectEdges/RegionSurfaceInputCombinations.
- [ ] DefaultEdges/RegionSurfaceInputCombinations.
- [ ] FullSurface/RegionSurfaceInputCombinations.
- [ ] SmallerRegion/RegionSurfaceInputCombinations.
- [ ] ClippedLargerRegion/RegionSurfaceInputCombinations.
- [ ] MultiRectCorners/RegionSurfaceInputCombinations.
- [ ] SurfaceInputRegions/SurfaceInputCombinations.
- [ ] ToplevelInputRegions/ToplevelInputCombinations.
- [ ] WlShellSubsurfaces/SubsurfaceTest.
- [ ] XdgShellV6Subsurfaces/SubsurfaceTest.
- [ ] XdgShellStableSubsurfaces/SubsurfaceTest.
- [ ] TouchInputSubsurfaces/SubsurfaceTest.
- [ ] WlShellSubsurfaces/SubsurfaceMultilevelTest.
- [ ] XdgShellV6Subsurfaces/SubsurfaceMultilevelTest.
- [ ] XdgShellStableSubsurfaces/SubsurfaceMultilevelTest.
- [ ] TouchInputSubsurfaces/SubsurfaceMultilevelTest.
- [ ] Default/XdgPopupPositionerTest.
- [ ] Anchor/XdgPopupPositionerTest.
- [ ] Gravity/XdgPopupPositionerTest.
- [ ] AnchorRect/XdgPopupPositionerTest.
- [ ] XdgPopupStable/XdgPopupTest.
- [ ] XdgPopupUnstableV6/XdgPopupTest.
- [ ] LayerShellPopup/XdgPopupTest.
- [ ] Anchors/LayerSurfaceErrorsTest.
- [ ] Anchor/LayerSurfaceLayoutTest.
- [ ] Layer/LayerSurfaceLayerTest.
